### PR TITLE
regulations: update models

### PR DESCRIPTION
**Pull request by hermannm**
### Changes

- change `Regime` model from covering a single regime number to covering a range of numbers (this is what regimes actually mean in the law, the prior model was flawed)
  - add `regime_number` field to `Regulation`
- change `Paragraph` to be connected to either a regulation, category or sub-category (there are examples in the law of paragraphs right under a category header, so not connected to a regulation - this is to support that)
- add `Meta` class with `constraints` to models to enforce rules between models (e.g. regime number ranges, paragraph parents, etc.)

### CODE REVIEW

**Review by danielmursa — APPROVED** [review]

**Comment by danielmursa** [comment]
I only have one suggestion, it is for the moment, where we change the models many times, until we find the final model, we can delete the first migrations each time and in this way the first migration is always correct.
what do you think?

**Comment by hermannm** [comment]
> I only have one suggestion, it is for the moment, where we change the models many times, until we find the final model, we can delete the first migrations each time and in this way the first migration is always correct. what do you think?

@danielmursa Yeah, I would agree, but that's why I asked if anyone had migrated database models locally. Apparently @KatjaSi had done this, so then I figured that we wouldn't wanna break her DB by making backwards-incompatible migrations. But maybe we should just reset the DB until we get the correct models?

**Comment by danielmursa** [comment]
yes correct, we can reset our db every time, because we are always local, so it does not cause any errors, then when the deployment will be performed, we would not do it anymore

**Comment by hermannm** [comment]
> yes correct, we can reset our db every time, because we are always local, so it does not cause any errors, then when the deployment will be performed, we would not do it anymore

Alright, talked to Katja now, and it's fine to reset migrations. Merging with that now.

**Pull request merged**
